# Generated by Django 2.2.17 on 2021-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=30, unique=True)),
                ('categoryPicture', models.ImageField(upload_to='')),
                ('categoryDescription', models.CharField(max_length=200)),
            ],
        ),
    ]
