# Generated by Django 2.2.17 on 2021-03-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_10e_app', '0002_auto_20210310_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=30, unique=True)),
                ('eventDescription', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('numberInterested', models.IntegerField(max_length=5)),
                ('eventPicture', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=8)),
                ('averageRating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_10e_app.Category')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_10e_app.UserProfile')),
            ],
        ),
    ]
