# Generated by Django 2.2.17 on 2021-03-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_10e_app', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='numberInterested',
            field=models.IntegerField(),
        ),
    ]
