# Generated by Django 2.2.17 on 2021-03-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_10e_app', '0004_auto_20210310_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_10e_app.Event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_10e_app.UserProfile')),
            ],
        ),
    ]
