# Generated by Django 2.2.17 on 2021-03-10 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_10e_app', '0005_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField()),
                ('comment', models.CharField(max_length=100)),
                ('eventName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_10e_app.Event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_10e_app.UserProfile')),
            ],
        ),
    ]
