# Generated by Django 2.2.17 on 2021-04-01 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='category_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('DOB', models.DateField()),
                ('profilePicture', models.ImageField(blank=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('startDate', models.DateField(default=None)),
                ('startTime', models.TimeField(default=None)),
                ('numberInterested', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='event_images/')),
                ('address', models.CharField(max_length=40)),
                ('postcode', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventastic.Category')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventastic.UserProfile')),
                ('usersInterested', models.ManyToManyField(blank=True, related_name='interest', to='eventastic.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventastic.Event')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventastic.UserProfile')),
            ],
        ),
    ]
