# Generated by Django 2.2.17 on 2021-03-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eventastic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, upload_to='event_images/'),
        ),
    ]
