# Generated by Django 2.2.17 on 2021-03-15 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventastic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='eventName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='categoryPicture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='eventName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventPicture',
            new_name='picture',
        ),
    ]
