# Generated by Django 2.2.17 on 2021-03-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventastic', '0002_auto_20210315_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='averageRating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='numberInterested',
        ),
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
