# Generated by Django 2.2.17 on 2021-04-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventastic', '0002_auto_20210404_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
