# Generated by Django 2.2.17 on 2021-03-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventastic', '0002_auto_20210320_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='usersInterested',
            field=models.ManyToManyField(blank=True, default=None, related_name='interest', to='eventastic.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Attend',
        ),
    ]
