# Generated by Django 2.2.17 on 2021-03-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('eventastic', '0003_auto_20210327_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='usersInterested',
            field=models.ManyToManyField(blank=True, related_name='interest', to='eventastic.UserProfile'),
        ),
    ]
