# Generated by Django 2.2.17 on 2021-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventastic', '0006_auto_20210315_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
