# Generated by Django 2.2.17 on 2021-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventastic', '0007_auto_20210315_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='averageRating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='event',
            name='numberInterested',
            field=models.IntegerField(default=0),
        ),
    ]
