# Generated by Django 2.2.17 on 2021-03-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventastic', '0010_auto_20210318_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
